// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3XfP8cIICuztgrdxcr3gvggfY1V-N084',
    appId: '1:958281447142:web:f160968c061a40eb89ed27',
    messagingSenderId: '958281447142',
    projectId: 'fishingbuild',
    authDomain: 'fishingbuild.firebaseapp.com',
    storageBucket: 'fishingbuild.firebasestorage.app',
    measurementId: 'G-SDGJ3JBESR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBIQ396RXjmIqXkhM3yFti2Yy55hYNjtU',
    appId: '1:958281447142:android:02b9ba2952cc6f0189ed27',
    messagingSenderId: '958281447142',
    projectId: 'fishingbuild',
    storageBucket: 'fishingbuild.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsS2DJs6KIUl33DPgtldQEkCDdj22KNSQ',
    appId: '1:958281447142:ios:74f22b9c0bcf2d1989ed27',
    messagingSenderId: '958281447142',
    projectId: 'fishingbuild',
    storageBucket: 'fishingbuild.firebasestorage.app',
    iosBundleId: 'com.jinhwan.fishingBuild',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsS2DJs6KIUl33DPgtldQEkCDdj22KNSQ',
    appId: '1:958281447142:ios:74f22b9c0bcf2d1989ed27',
    messagingSenderId: '958281447142',
    projectId: 'fishingbuild',
    storageBucket: 'fishingbuild.firebasestorage.app',
    iosBundleId: 'com.jinhwan.fishingBuild',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3XfP8cIICuztgrdxcr3gvggfY1V-N084',
    appId: '1:958281447142:web:99f16e03fe38b03989ed27',
    messagingSenderId: '958281447142',
    projectId: 'fishingbuild',
    authDomain: 'fishingbuild.firebaseapp.com',
    storageBucket: 'fishingbuild.firebasestorage.app',
    measurementId: 'G-X3N8ENLDHY',
  );
}
